#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Demo.Resource", IsApplication=true)]

namespace Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Gauge.Resource.Array.rangeColors = global::Demo.Resource.Array.rangeColors;
			global::Gauge.Resource.Array.ranges = global::Demo.Resource.Array.ranges;
			global::Gauge.Resource.Attribute.divisions = global::Demo.Resource.Attribute.divisions;
			global::Gauge.Resource.Attribute.innerRimBorderWidth = global::Demo.Resource.Attribute.innerRimBorderWidth;
			global::Gauge.Resource.Attribute.innerRimWidth = global::Demo.Resource.Attribute.innerRimWidth;
			global::Gauge.Resource.Attribute.needleHeight = global::Demo.Resource.Attribute.needleHeight;
			global::Gauge.Resource.Attribute.needleWidth = global::Demo.Resource.Attribute.needleWidth;
			global::Gauge.Resource.Attribute.outerBorderWidth = global::Demo.Resource.Attribute.outerBorderWidth;
			global::Gauge.Resource.Attribute.outerRimWidth = global::Demo.Resource.Attribute.outerRimWidth;
			global::Gauge.Resource.Attribute.outerShadowWidth = global::Demo.Resource.Attribute.outerShadowWidth;
			global::Gauge.Resource.Attribute.rangeColors = global::Demo.Resource.Attribute.rangeColors;
			global::Gauge.Resource.Attribute.rangeValues = global::Demo.Resource.Attribute.rangeValues;
			global::Gauge.Resource.Attribute.scaleEndAngle = global::Demo.Resource.Attribute.scaleEndAngle;
			global::Gauge.Resource.Attribute.scaleEndValue = global::Demo.Resource.Attribute.scaleEndValue;
			global::Gauge.Resource.Attribute.scalePosition = global::Demo.Resource.Attribute.scalePosition;
			global::Gauge.Resource.Attribute.scaleStartAngle = global::Demo.Resource.Attribute.scaleStartAngle;
			global::Gauge.Resource.Attribute.scaleStartValue = global::Demo.Resource.Attribute.scaleStartValue;
			global::Gauge.Resource.Attribute.showInnerRim = global::Demo.Resource.Attribute.showInnerRim;
			global::Gauge.Resource.Attribute.showNeedle = global::Demo.Resource.Attribute.showNeedle;
			global::Gauge.Resource.Attribute.showOuterBorder = global::Demo.Resource.Attribute.showOuterBorder;
			global::Gauge.Resource.Attribute.showOuterRim = global::Demo.Resource.Attribute.showOuterRim;
			global::Gauge.Resource.Attribute.showOuterShadow = global::Demo.Resource.Attribute.showOuterShadow;
			global::Gauge.Resource.Attribute.showRanges = global::Demo.Resource.Attribute.showRanges;
			global::Gauge.Resource.Attribute.showScale = global::Demo.Resource.Attribute.showScale;
			global::Gauge.Resource.Attribute.showText = global::Demo.Resource.Attribute.showText;
			global::Gauge.Resource.Attribute.subdivisions = global::Demo.Resource.Attribute.subdivisions;
			global::Gauge.Resource.Attribute.textShadowColor = global::Demo.Resource.Attribute.textShadowColor;
			global::Gauge.Resource.Attribute.textUnit = global::Demo.Resource.Attribute.textUnit;
			global::Gauge.Resource.Attribute.textUnitColor = global::Demo.Resource.Attribute.textUnitColor;
			global::Gauge.Resource.Attribute.textUnitSize = global::Demo.Resource.Attribute.textUnitSize;
			global::Gauge.Resource.Attribute.textValue = global::Demo.Resource.Attribute.textValue;
			global::Gauge.Resource.Attribute.textValueColor = global::Demo.Resource.Attribute.textValueColor;
			global::Gauge.Resource.Attribute.textValueSize = global::Demo.Resource.Attribute.textValueSize;
			global::Gauge.Resource.Drawable.brushed_alu = global::Demo.Resource.Drawable.brushed_alu;
			global::Gauge.Resource.Drawable.brushed_alu2 = global::Demo.Resource.Drawable.brushed_alu2;
			global::Gauge.Resource.Drawable.carbon_fibre = global::Demo.Resource.Drawable.carbon_fibre;
			global::Gauge.Resource.Drawable.light_alu = global::Demo.Resource.Drawable.light_alu;
			global::Gauge.Resource.String.ApplicationName = global::Demo.Resource.String.ApplicationName;
			global::Gauge.Resource.String.Hello = global::Demo.Resource.String.Hello;
			global::Gauge.Resource.Styleable.GaugeView = global::Demo.Resource.Styleable.GaugeView;
			global::Gauge.Resource.Styleable.GaugeView_divisions = global::Demo.Resource.Styleable.GaugeView_divisions;
			global::Gauge.Resource.Styleable.GaugeView_innerRimBorderWidth = global::Demo.Resource.Styleable.GaugeView_innerRimBorderWidth;
			global::Gauge.Resource.Styleable.GaugeView_innerRimWidth = global::Demo.Resource.Styleable.GaugeView_innerRimWidth;
			global::Gauge.Resource.Styleable.GaugeView_needleHeight = global::Demo.Resource.Styleable.GaugeView_needleHeight;
			global::Gauge.Resource.Styleable.GaugeView_needleWidth = global::Demo.Resource.Styleable.GaugeView_needleWidth;
			global::Gauge.Resource.Styleable.GaugeView_outerBorderWidth = global::Demo.Resource.Styleable.GaugeView_outerBorderWidth;
			global::Gauge.Resource.Styleable.GaugeView_outerRimWidth = global::Demo.Resource.Styleable.GaugeView_outerRimWidth;
			global::Gauge.Resource.Styleable.GaugeView_outerShadowWidth = global::Demo.Resource.Styleable.GaugeView_outerShadowWidth;
			global::Gauge.Resource.Styleable.GaugeView_rangeColors = global::Demo.Resource.Styleable.GaugeView_rangeColors;
			global::Gauge.Resource.Styleable.GaugeView_rangeValues = global::Demo.Resource.Styleable.GaugeView_rangeValues;
			global::Gauge.Resource.Styleable.GaugeView_scaleEndAngle = global::Demo.Resource.Styleable.GaugeView_scaleEndAngle;
			global::Gauge.Resource.Styleable.GaugeView_scaleEndValue = global::Demo.Resource.Styleable.GaugeView_scaleEndValue;
			global::Gauge.Resource.Styleable.GaugeView_scalePosition = global::Demo.Resource.Styleable.GaugeView_scalePosition;
			global::Gauge.Resource.Styleable.GaugeView_scaleStartAngle = global::Demo.Resource.Styleable.GaugeView_scaleStartAngle;
			global::Gauge.Resource.Styleable.GaugeView_scaleStartValue = global::Demo.Resource.Styleable.GaugeView_scaleStartValue;
			global::Gauge.Resource.Styleable.GaugeView_showInnerRim = global::Demo.Resource.Styleable.GaugeView_showInnerRim;
			global::Gauge.Resource.Styleable.GaugeView_showNeedle = global::Demo.Resource.Styleable.GaugeView_showNeedle;
			global::Gauge.Resource.Styleable.GaugeView_showOuterBorder = global::Demo.Resource.Styleable.GaugeView_showOuterBorder;
			global::Gauge.Resource.Styleable.GaugeView_showOuterRim = global::Demo.Resource.Styleable.GaugeView_showOuterRim;
			global::Gauge.Resource.Styleable.GaugeView_showOuterShadow = global::Demo.Resource.Styleable.GaugeView_showOuterShadow;
			global::Gauge.Resource.Styleable.GaugeView_showRanges = global::Demo.Resource.Styleable.GaugeView_showRanges;
			global::Gauge.Resource.Styleable.GaugeView_showScale = global::Demo.Resource.Styleable.GaugeView_showScale;
			global::Gauge.Resource.Styleable.GaugeView_showText = global::Demo.Resource.Styleable.GaugeView_showText;
			global::Gauge.Resource.Styleable.GaugeView_subdivisions = global::Demo.Resource.Styleable.GaugeView_subdivisions;
			global::Gauge.Resource.Styleable.GaugeView_textShadowColor = global::Demo.Resource.Styleable.GaugeView_textShadowColor;
			global::Gauge.Resource.Styleable.GaugeView_textUnit = global::Demo.Resource.Styleable.GaugeView_textUnit;
			global::Gauge.Resource.Styleable.GaugeView_textUnitColor = global::Demo.Resource.Styleable.GaugeView_textUnitColor;
			global::Gauge.Resource.Styleable.GaugeView_textUnitSize = global::Demo.Resource.Styleable.GaugeView_textUnitSize;
			global::Gauge.Resource.Styleable.GaugeView_textValue = global::Demo.Resource.Styleable.GaugeView_textValue;
			global::Gauge.Resource.Styleable.GaugeView_textValueColor = global::Demo.Resource.Styleable.GaugeView_textValueColor;
			global::Gauge.Resource.Styleable.GaugeView_textValueSize = global::Demo.Resource.Styleable.GaugeView_textValueSize;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040001
			public const int rangeColors = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int ranges = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010014
			public const int divisions = 2130771988;
			
			// aapt resource value: 0x7f01000c
			public const int innerRimBorderWidth = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int innerRimWidth = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public const int needleHeight = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int needleWidth = 2130771981;
			
			// aapt resource value: 0x7f010009
			public const int outerBorderWidth = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int outerRimWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int outerShadowWidth = 2130771976;
			
			// aapt resource value: 0x7f010017
			public const int rangeColors = 2130771991;
			
			// aapt resource value: 0x7f010016
			public const int rangeValues = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int scaleEndAngle = 2130771987;
			
			// aapt resource value: 0x7f010011
			public const int scaleEndValue = 2130771985;
			
			// aapt resource value: 0x7f01000f
			public const int scalePosition = 2130771983;
			
			// aapt resource value: 0x7f010012
			public const int scaleStartAngle = 2130771986;
			
			// aapt resource value: 0x7f010010
			public const int scaleStartValue = 2130771984;
			
			// aapt resource value: 0x7f010003
			public const int showInnerRim = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int showNeedle = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int showOuterBorder = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int showOuterRim = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int showOuterShadow = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int showRanges = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int showScale = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int showText = 2130771975;
			
			// aapt resource value: 0x7f010015
			public const int subdivisions = 2130771989;
			
			// aapt resource value: 0x7f01001e
			public const int textShadowColor = 2130771998;
			
			// aapt resource value: 0x7f01001b
			public const int textUnit = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int textUnitColor = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int textUnitSize = 2130771997;
			
			// aapt resource value: 0x7f010018
			public const int textValue = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int textValueColor = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int textValueSize = 2130771994;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int brushed_alu = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int brushed_alu2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int carbon_fibre = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int light_alu = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int gauge_view1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int gauge_view2 = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] GaugeView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998};
			
			// aapt resource value: 20
			public const int GaugeView_divisions = 20;
			
			// aapt resource value: 12
			public const int GaugeView_innerRimBorderWidth = 12;
			
			// aapt resource value: 11
			public const int GaugeView_innerRimWidth = 11;
			
			// aapt resource value: 14
			public const int GaugeView_needleHeight = 14;
			
			// aapt resource value: 13
			public const int GaugeView_needleWidth = 13;
			
			// aapt resource value: 9
			public const int GaugeView_outerBorderWidth = 9;
			
			// aapt resource value: 10
			public const int GaugeView_outerRimWidth = 10;
			
			// aapt resource value: 8
			public const int GaugeView_outerShadowWidth = 8;
			
			// aapt resource value: 23
			public const int GaugeView_rangeColors = 23;
			
			// aapt resource value: 22
			public const int GaugeView_rangeValues = 22;
			
			// aapt resource value: 19
			public const int GaugeView_scaleEndAngle = 19;
			
			// aapt resource value: 17
			public const int GaugeView_scaleEndValue = 17;
			
			// aapt resource value: 15
			public const int GaugeView_scalePosition = 15;
			
			// aapt resource value: 18
			public const int GaugeView_scaleStartAngle = 18;
			
			// aapt resource value: 16
			public const int GaugeView_scaleStartValue = 16;
			
			// aapt resource value: 3
			public const int GaugeView_showInnerRim = 3;
			
			// aapt resource value: 4
			public const int GaugeView_showNeedle = 4;
			
			// aapt resource value: 1
			public const int GaugeView_showOuterBorder = 1;
			
			// aapt resource value: 2
			public const int GaugeView_showOuterRim = 2;
			
			// aapt resource value: 0
			public const int GaugeView_showOuterShadow = 0;
			
			// aapt resource value: 6
			public const int GaugeView_showRanges = 6;
			
			// aapt resource value: 5
			public const int GaugeView_showScale = 5;
			
			// aapt resource value: 7
			public const int GaugeView_showText = 7;
			
			// aapt resource value: 21
			public const int GaugeView_subdivisions = 21;
			
			// aapt resource value: 30
			public const int GaugeView_textShadowColor = 30;
			
			// aapt resource value: 27
			public const int GaugeView_textUnit = 27;
			
			// aapt resource value: 28
			public const int GaugeView_textUnitColor = 28;
			
			// aapt resource value: 29
			public const int GaugeView_textUnitSize = 29;
			
			// aapt resource value: 24
			public const int GaugeView_textValue = 24;
			
			// aapt resource value: 25
			public const int GaugeView_textValueColor = 25;
			
			// aapt resource value: 26
			public const int GaugeView_textValueSize = 26;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
