#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Gauge.Resource", IsApplication=false)]

namespace Gauge
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f030001
			public static int rangeColors = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int ranges = 2130903040;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010014
			public static int divisions = 2130771988;
			
			// aapt resource value: 0x7f01000c
			public static int innerRimBorderWidth = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public static int innerRimWidth = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public static int needleHeight = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public static int needleWidth = 2130771981;
			
			// aapt resource value: 0x7f010009
			public static int outerBorderWidth = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public static int outerRimWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public static int outerShadowWidth = 2130771976;
			
			// aapt resource value: 0x7f010017
			public static int rangeColors = 2130771991;
			
			// aapt resource value: 0x7f010016
			public static int rangeValues = 2130771990;
			
			// aapt resource value: 0x7f010013
			public static int scaleEndAngle = 2130771987;
			
			// aapt resource value: 0x7f010011
			public static int scaleEndValue = 2130771985;
			
			// aapt resource value: 0x7f01000f
			public static int scalePosition = 2130771983;
			
			// aapt resource value: 0x7f010012
			public static int scaleStartAngle = 2130771986;
			
			// aapt resource value: 0x7f010010
			public static int scaleStartValue = 2130771984;
			
			// aapt resource value: 0x7f010003
			public static int showInnerRim = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int showNeedle = 2130771972;
			
			// aapt resource value: 0x7f010001
			public static int showOuterBorder = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int showOuterRim = 2130771970;
			
			// aapt resource value: 0x7f010000
			public static int showOuterShadow = 2130771968;
			
			// aapt resource value: 0x7f010006
			public static int showRanges = 2130771974;
			
			// aapt resource value: 0x7f010005
			public static int showScale = 2130771973;
			
			// aapt resource value: 0x7f010007
			public static int showText = 2130771975;
			
			// aapt resource value: 0x7f010015
			public static int subdivisions = 2130771989;
			
			// aapt resource value: 0x7f01001e
			public static int textShadowColor = 2130771998;
			
			// aapt resource value: 0x7f01001b
			public static int textUnit = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public static int textUnitColor = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public static int textUnitSize = 2130771997;
			
			// aapt resource value: 0x7f010018
			public static int textValue = 2130771992;
			
			// aapt resource value: 0x7f010019
			public static int textValueColor = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public static int textValueSize = 2130771994;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int brushed_alu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int brushed_alu2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int carbon_fibre = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int light_alu = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] GaugeView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998};
			
			// aapt resource value: 20
			public static int GaugeView_divisions = 20;
			
			// aapt resource value: 12
			public static int GaugeView_innerRimBorderWidth = 12;
			
			// aapt resource value: 11
			public static int GaugeView_innerRimWidth = 11;
			
			// aapt resource value: 14
			public static int GaugeView_needleHeight = 14;
			
			// aapt resource value: 13
			public static int GaugeView_needleWidth = 13;
			
			// aapt resource value: 9
			public static int GaugeView_outerBorderWidth = 9;
			
			// aapt resource value: 10
			public static int GaugeView_outerRimWidth = 10;
			
			// aapt resource value: 8
			public static int GaugeView_outerShadowWidth = 8;
			
			// aapt resource value: 23
			public static int GaugeView_rangeColors = 23;
			
			// aapt resource value: 22
			public static int GaugeView_rangeValues = 22;
			
			// aapt resource value: 19
			public static int GaugeView_scaleEndAngle = 19;
			
			// aapt resource value: 17
			public static int GaugeView_scaleEndValue = 17;
			
			// aapt resource value: 15
			public static int GaugeView_scalePosition = 15;
			
			// aapt resource value: 18
			public static int GaugeView_scaleStartAngle = 18;
			
			// aapt resource value: 16
			public static int GaugeView_scaleStartValue = 16;
			
			// aapt resource value: 3
			public static int GaugeView_showInnerRim = 3;
			
			// aapt resource value: 4
			public static int GaugeView_showNeedle = 4;
			
			// aapt resource value: 1
			public static int GaugeView_showOuterBorder = 1;
			
			// aapt resource value: 2
			public static int GaugeView_showOuterRim = 2;
			
			// aapt resource value: 0
			public static int GaugeView_showOuterShadow = 0;
			
			// aapt resource value: 6
			public static int GaugeView_showRanges = 6;
			
			// aapt resource value: 5
			public static int GaugeView_showScale = 5;
			
			// aapt resource value: 7
			public static int GaugeView_showText = 7;
			
			// aapt resource value: 21
			public static int GaugeView_subdivisions = 21;
			
			// aapt resource value: 30
			public static int GaugeView_textShadowColor = 30;
			
			// aapt resource value: 27
			public static int GaugeView_textUnit = 27;
			
			// aapt resource value: 28
			public static int GaugeView_textUnitColor = 28;
			
			// aapt resource value: 29
			public static int GaugeView_textUnitSize = 29;
			
			// aapt resource value: 24
			public static int GaugeView_textValue = 24;
			
			// aapt resource value: 25
			public static int GaugeView_textValueColor = 25;
			
			// aapt resource value: 26
			public static int GaugeView_textValueSize = 26;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
